#!/bin/bash
#OWNER: MARK BARTLETT
#DATE: 11/02/2018
#THIS IS THE CAPTURE SCRIPT##
#LOCATION OF CONF FILE#
source /opt/BH/BHCOL/CONF/bh.conf
#source /opt/BHCOL/CONF/bh.conf
#LOCATION OF FUNCTION FILE#
#source /opt/BHCOL/FUNCS/funky.func
source /opt/BH/BHCOL/FUNCS/funky.func

#FUNCTION TO CHECK FOR RUN LOG DIRECTORY#
check_runlogdirectory
#FUNCTION TO CHECK FOR RUN LOG FILE#
check_runlogfile
#FUNCTION TO START THE CAPTURE#
cap_start

#FUNCTION TO CHECK THE FILE SIZE OF THE CAPTURE FILE BEFORE COMPRESSION#
check_filesizeuc

#FUNCTION TO COMPRESS THE CAPTURE FILE#
file_compress

#FUNCTION TO CHECK THE FILE SIZE OF THE CAPTURE FILE AFTER COMPRESSION#
check_filesizeac

#FUNCTION TO CHECK FOR TRANSPORT DIRECTORY#
check_transportdir
#FUNCTION TO CHECK FOR TRANSPORT DATE DIRECTORY#
check_transportdatedir
#FUNCTION TO SET FILE PERMISIONS FOR CAPTURE FILES#
set_fileperms
#FUNCTION TO WRITE CAPTURE RUN INFO TO LOG FILE#
cap_info
